server:
  port: 8102
logging:
  level:
    org.springframework.cloud: 'DEBUG'
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pp963078656/cloud.git
          searchPaths: config
          username: 963078656@qq.com
          password: lipeng@19871218
          label: master
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serice-url:
      defaultZone: http://localhost:8101/eureka/
